const axios = require('axios')

let handler = async (m, { bot, args }) => {
  if (!args[0]) {
    return m.reply('❌ *Penggunaan:*\n/text2anime <deskripsi>')
  }

  let text = args.join(' ')
  
  try {
    await bot.sendChatAction(m.chat, 'typing')

    m.reply('⏳ _Sedang membuat gambar anime..._')

    let apiUrl = `https://api.dashx.biz.id/api/AI/text2anime?text=${encodeURIComponent(text)}&key=${dhx}`
    let response = await axios.get(apiUrl)
    
    if (!response.data || !response.data.success) {
      return m.reply('❌ Gagal membuat gambar anime')
    }

    let imageUrl = response.data.url

    await bot.sendChatAction(m.chat, 'upload_photo')

    const imageBuffer = await bot.getBuffer(imageUrl)

    await bot.sendPhoto(m.chat, imageBuffer, {
      caption: `🎨 *Text to Anime*\n\n📝 *Prompt:* ${text}\n\n_Generated by AI_`,
      parse_mode: 'Markdown',
      reply_to_message_id: m.message_id
    })

  } catch (e) {
    console.error(e)
    return m.reply('❌ Terjadi kesalahan: ' + e.message)
  }
}

handler.help = ['text2anime', 'txtanime']
handler.tags = ['ai']
handler.command = /^(text2anime|txt2anime|txtanime)$/i
handler.limit = true

module.exports = handler